name: gopaxe_logger
description: Gopaxe logger
version: 1.0.0
repository: https://github.com/gopaxe/gopaxe_logger.git
publish_to: none

environment:
  sdk: ^3.1.0

dependencies:
  encrypt: ^5.0.3
  intl: ^0.18.1
  # loggme: ^1.0.5 
  loggme: 
    git:
      url: https://github.com/Ofceab-Studio/loggme.git
    # path: ../demo_logging_with_telegram
    
  

dev_dependencies:
  lints: ^2.1.0
  build_runner: ^2.4.8
  test: ^1.24.0
  auto_exporter: ^2.0.1


platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:  

scripts:
  gen-build: 'dart run build_runner build && mv lib/export.dart lib/gopaxe_logger.dart'